package io.github.some_example_name.model;

public enum TextKey {
    MENU_SIGNUP_TEXT_BUTTON("menu.signuptextbutton"),
    MENU_GUEST_TEXT_BUTTON("menu.guesttextbutton"),
    MENU_BACK_TEXT_BUTTON("menu.backtextbutton"),
    MENU_USERNAME_TEXT_FIELD("menu.usernametextfield"),
    MENU_SECURITY_TEXT_FIELD("menu.seciritytextfield"),
    MENU_PASSWORD_TEXT_FILED("menu.passwordtextfiled"),
    MENU_SECURITY_LABEL("menu.secuiritylabel"),
    MENU_WIN_LABEL("menu.winlabel"),
    MENU_LOSE_LABEL("menu.loselabel"),
    MENU_SURVIVAL_LABEL("menu.servivallabel"),
    MENU_KILL_LABEL("menu.killlabel"),
    MENU_SCORE_LABEL("menu.scorelabel"),
    MENU_LOGIN_TEXT_BUTTON("menu.logintextbutton"),
    MENU_EXIT_GAME_TEXT_BUTTON("menu.exitgametextbutton"),
    MENU_CONTINUE_TEXT_BUTTON("menu.continuetextbutton"),
    MENU_CHOOSE_ABILITY_TEXT_BUTTON("menu.chooseabilitytextbutton"),
    MENU_FORGET_PASSWORD_DIALOG("menu.forgetpassworddialog"),
    MENU_ABILITY_DIALOG("menu.abilitydialo"),
    MENU_LEVEL_LABEL("menu.levellabel"),
    MENU_NEW_PASSWORD_LABEL("menu.newpasswordlabel"),
    MENU_CONFIRM_TEXT_BUTTON("menu.confirmtextbutton"),
    MENU_CANCEL_TEXT_BUTTON("menu.canceltextbutton"),
    MENU_SECURITY_QUESTION_LABEL("menu.secuirityquestionlabel"),
    MENU_SETTING_MENU_BUTTON("menu.settingmenubutton"),
    MENU_PREGAME_BUTTON("menu.pregamebutton"),
    MENU_SCOREBOARD_BUTTON("menu.scoreboardbutton"),
    MENU_TALENT_MENU_BUTTON("menu.talentmenubutton"),
    MENU_PROFILE_MENU_BUTTON("menu.profilemenubutton"),
    MENU_LAST_GAME_BUTTON("menu.lastgamebutton"),
    MENU_LOGOUT_BUTTON("menu.logoutbutton"),
    MENU_BW_TOGGLE("this.bwtoggle"),
    MENU_RESUME_BUTTON("menu.resumebutton"),
    MENU_GIVE_UP_BUTTON("menu.giveupbutton"),
    MENU_SAVE_AND_QUIT_BUTTON("menu.saveandquitbutton"),
    MENU_PAUSE_MENU_BUTTON("menu.pausemenubutton"),
    MENU_CHEAT_CODES_LABEL("menu.cheatcodeslabel"),
    MENU_CHEAT1("menu.cheat1"),
    MENU_CHEAT2("menu.cheat2"),
    MENU_CHEAT3("menu.cheat3"),
    MENU_CHEAT4("menu.cheat4"),
    MENU_CHEAT5("menu.cheat5"),
    MENU_PLAYER_ABILITY_LABEL("menu.playerabilitylabel"),
    MENU_HERO_SELECTION_BUTTON("menu.heroselectionbutton"),
    MENU_WEAPON_SELECTION_BUTTON("menu.weaponselectionbutton"),
    MENU_START_GAME_BUTTON("menu.startgamebutton"),
    MENU_TIME_LABEL("menu.timelabel"),
    MENU_NEW_USERNAME_TEXT_FIELD("menu.newusernametextfield"),
    MENU_CHANGE_AVATAR_BUTTON("menu.changeavatarbutton"),
    MENU_DELETE_ACCOUNT_BUTTON("menu.deleteacountbutton"),
    MENU_CHANGE_PASSWORD_BUTTON("menu.changepasswordbutton"),
    MENU_CHANGE_USERNAME_BUTTON("menu.changeusernamebutton"),
    MENU_SELECT_FILE_FROM_SYSTEM_BUTTON("menu.selectfilefromsystembutton"),
    MENU_PROFILE_LABEL("menu.profilelabel"),
    MENU_SCOREBOARD_LABEL("menu.scoreboardlabel"),
    MENU_USERNAME_LABEL("menu.usernamelabel"),
    MENU_SORT_BY_LABEL("menu.sortbylabel"),
    MENU_MUSIC_TOGGLE("menu.musictogle"),
    MENU_SFX_TOGGLE("menu.sfxtoggle"),
    MENU_AUTO_RELOAD_TOGGLE("menu.autoreloadtoggle"),
    MENU_SETTING_MENU_LABEL("menu.settingmenulabel"),
    MENU_MUSIC_VOLUME_LABEL("menu.musicvolumelabel"),
    MENU_CHOOSE_MUSIC_LABEL("menu.choosemusiclabel"),
    MENU_MOVE_UP_LABEL("menu.moveuplabel"),
    MENU_MOVE_DOWN_LABEL("menu.movedownlabel"),
    MENU_MOVE_RIGHT_LABEL("menu.moverightlabel"),
    MENU_MOVE_LEFT_LABEL("menu.moveleftlabel"),
    MENU_RELOAD_LABEL("menu.reloadlabel"),
    MENU_AUTO_AIM_LABEL("menu.autoaimlabel"),
    MENU_PAUSE_LABEL("menu.pauselabel"),
    MENU_TALENT_MENU_LABEL("menu.talentmenulabel"),
    MENU_CHARACTER_LABEL("menu.charectorlabel"),
    MENU_CHEAT1TALENT("menu.cheat1talent"),
    MENU_CHEAT2TALENT("menu.cheat2talent"),
    MENU_CHEAT3TALENT("menu.cheat3talent"),
    MENU_CHEAT4TALENT("menu.cheat4talent"),
    MENU_CHEAT5TALENT("menu.cheat5talent"),
    MENU_DESCRIPTION_LAEBEL("menu.descriptionlaebel"),
    MENU_VATALITY_DES("menu.vatalitydes"),
    MENU_DAMAGER_DES("menu.damagerdes"),
    MENU_PROCREASE_DES("menu.procreasedes"),
    MENU_AMMOCREASE_DES("menu.ammocreasedes"),
    MENU_SPEEDY_DES("menu.speedydes"),
    MENU_FORGETPASS_ERROR1("menu.forgetpasserror1"),
    MENU_FORGETPASS_ERROR2("menu.forgetpasserror2"),
    MENU_FORGETPASS_ERROR3("menu.forgetpasserror3"),
    MENU_FORGETPASS_ERROR4("menu.forgetpasserror4"),
    MENU_LOGIN_ERROR1("menu.loginerror1"),
    MENU_LOGIN_ERROR2("menu.loginerror2"),
    MENU_LOGIN_ERROR3("menu.loginerror3"),
    MENU_START_GAME_ERROR1("menu.startgameerror1"),
    MENU_START_GAME_ERROR2("menu.startgameerror2"),
    MENU_START_GAME_ERROR3("menu.startgameerror3"),
    MENU_CHANGE_PASSWORD_ERROR("menu.changepassworderror"),
    MENU_CHANGE_USERNAME_ERROR("menu.changeusernameerror"),
    MENU_REGISTER_ERROR1("menu.registererror1"),
    MENU_REGISTER_ERROR2("menu.registererror2"),
    MENU_REGISTER_ERROR3("menu.registererror3");

    private final String key;

    TextKey(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
